### ISSUE TITLE
Foro: El tipo de foro está en inglés, General discussion 

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#13]
**Problema:**
Cuando se crea un tema de foro, solo hay un tipo de foro "General discussion" el cual deberían estar en español

**Comportamiento deseado**
-Que la página muestre todas sus elementos en el idioma de la página, en este caso es español.

**Links:** 
Foro: https://plataforma.bioleft.org/node/add/forum?forum_id=1

**Comment by ludwigrubio** [comment]
Se realizó la traducción y se dejo en el archivo de configuraciones para futuras instalaciones.

**Comment by fernandiie** [comment]
El texto "General discussion" ha sido traducido a "Discusión general".
