### ISSUE TITLE
La plataforma Bioleft no tiene un Favicon

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#15]
**Problema:**
La plataforma Bioleft no tiene un Favicon a diferencia de la página de Bioleft que si tiene. 

**Comportamiento deseado**
-Que tenga un Favicon 
-Que sean consistentes las páginas relacionadas a Bioleft, ¿tal vez el mismo Favicon? 

**Links:** 
Con favicon: Bioleft: http://bioleft.org/ 
Sin favicon: Plataforma web de Bioleft: https://plataforma.bioleft.org

**Comment by ludwigrubio** [comment]
Se añadió favicon.ico

**Comment by fernandiie** [comment]
El favicon ahora es visible en la plataforma Bioleft, verificado en el dominio de pruebas. 
Este "issue" es cerrado ahora.
