### ISSUE TITLE
Las semillas creadas por el mismo usuario no son visibles para él a traves del catalogo de semillas

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#16]
**Problema:**
Las semillas creadas por el mismo usuario no son visibles para él a traves del catalogo de semillas, ¿es esto intencional?

**Comportamiento deseado**
Que todas las semillas sean visibles 

**Links:** 
https://plataforma.bioleft.org/catalogo-semillas

**Comment by ludwigrubio** [comment]
Debido a que el objetivo de este listado es el intercambio de semillas, y además, se creó un nuevo listado más visual donde se muestran todas las semillas en general (incluyendo las propias del usuario), este ya no es un requerimiento necesario.

**Comment by fernandiie** [comment]
Gracias! Agrego el enlace **provisional** nuevo catálogo -> http://bioleft.datalud.com/
