### ISSUE TITLE
Página no encontrada si no hay información en el cuderno de campo

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#2]
**Problema:**
Si el usuario no ha creado ningún cuaderno de campo y hace clic en el botón "Listado de Cuaderno de campo", la plataforma es redireccionada a "Página no encontrada".

**Comportamiento deseado**
-Que la aplicación muestre mensajes más informativos, en este caso algo como "Aún no hay cuadernos de campo creados. Creá tu primer cuaderno de campo." como ya se ha usado en otros casos.
-Otra opción sería que el botón "Listado de Cuaderno de campo" apareciera deshabilitado cuando no haya información de los cuadernos de campo.

**Links:**
Botón "Listado de Cuaderno de campo": https://plataforma.bioleft.org/user/36
Página no encontrada: https://plataforma.bioleft.org/cuaderno-de-campo

**Comment by ludwigrubio** [comment]
Se cambió por "Ir a mi cuaderno de campo".

Se queda siempre habilitado para que pueda visitar la sección, y así consultar o crear ya sea un lote o un campo, según su necesidad.

**Comment by fernandiie** [comment]
Verificado, "Página encontrada" ya no aparece después de hacer clic en "Listado de Cuaderno de campo", ahora se cambia a otra página que dice, "Aún no hay lotes creados. Crea tu primer lote.". 



**Texto anterior:** 
Últimos cuadernos de campo - Título del bloque
Aún no hay cuadernos de campo creados. Creá tu primer cuaderno de campo. - Texto dentro del bloque
Listado de Cuaderno de campo - Texto del botón dentro del bloque

**Texto actual:**
Cuaderno de campo - Título del bloque
Aún no hay nada en tu cuaderno de campo. - Texto dentro del bloque
Ir a mi cuaderno de campo - Texto del botón dentro del bloque

**Comment by fernandiie** [comment]
Enlace provisional donde se hizo la verificacion:
http://bioleft.datalud.com/lote
