### ISSUE TITLE
Este mensaje debe estar en español->  "Access denied. You must log in to view this page." 

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#20]
**Problema:**
Al intentar editar un usuario, y se está deslogueado, se muestra un mensaje en Ingles "Access denied. You must log in to view this page.". Este es un mensaje general de permisos que debe ser traducido.

**Comportamiento deseado**
-Que la paǵina sea consistente con el idoma, en este caso los mensajes deben estar en español.

**Links:** 
https://plataforma.bioleft.org/user/login?destination=/user/35/edit

**Comment by ludwigrubio** [comment]
Se tradujo el texto a: "Acceso no permitido. Debes iniciar sesión para ver esta página."

**Comment by fernandiie** [comment]
Verificado, el mensaje ha sido traducido a "Acceso no permitido. Debes iniciar sesión para ver esta página." 

El mensaje se obtuvo realizando diversas operaciones que requieren que el usuario haya iniciado sesión, tales como: 

-Mis semillas
-Ver transacción
