### ISSUE TITLE
Añadir semilla-> Mensajes de ayuda en inglés

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#23]
**Problema:**
Se muestra una opción en la parte superior que índica "Estado de la públicación" con un mensaje de ayuda en Inglés, se recomienda quitar dicha opción o enriquecer la forma de describirlo.

**Comportamiento deseado**
-Que todos los elementos de la página sean consistentes en su texto, que muestren el texto en el idioma correcto. 

**Links:** 
Añadir Mis semillas: https://plataforma.bioleft.org/admin/structure/semilla/add/mis_semillas

**Comment by ludwigrubio** [comment]
El texto de ayuda se modificó por:

"Activa la casilla para indicar que este contenido está publicado. 

 Puede ser útil desactivarlo cuando, por ejemplo, no tengas más semillas de este tipo, o ya no deseas que sea visible por lxs demás usuarixs."

**Comment by fernandiie** [comment]
Verificado. 

El mensaje cambió:

 **de** "A boolean indicating whether the semilla is published" 

**a**  
"Activa la casilla para indicar que este contenido está publicado.

Puede ser útil desactivarlo cuando, por ejemplo, no tengas más semillas de este tipo, o ya no deseas que sea visible por lxs demás usuarixs."

**Comment by fernandiie** [comment]
Verificado en el enlace provisional:
 http://bioleft.datalud.com/admin/structure/semilla/add/mis_semillas
