### ISSUE TITLE
Catálogo: aparecen semillas que no tienen especie

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#25]
**Problema:**
En el catalogo no deberían aparecer semillas sin especie. 

**Comportamiento deseado**
-Que solo se muestren semillas que tenga la información completa. 

**Links:** 
Catálogo semillas: https://plataforma.bioleft.org/catalogo-semillas

**Comment by ludwigrubio** [comment]
Se corrigió el problema en los siguientes listados:

* Mis semillas
* Catálogo de semillas
* Página de inicio

**Comment by fernandiie** [comment]
He intentado verificar este "issue" pero no he podido crear semillas sin el campo especie. Anteriormente esto era posible. 

Comparando con una versión anterior, las semillas que se podían guardar sin especie era desplegadas. 

Lo cual me hace inferir que las semillas que no tenían especie habían sido creadas como semillas mejoradas, podemos llamarlas semillas madres, entonces,  entonces la semillas creadas podrían ser llamadas semillas hijas, las cuales heredan información de la madre como la especie, esto no sucedía. 

Ahora las semillas hijas si están heredando de manera adecuada y dicha información está siendo desplegada en las siguiente secciones: 
* Mis semillas
* Catálogo de semillas
* Página de inicio

Hay otras secciones donde no es visible y se abrirá un nuevo issue para discutir más a fondo. 

Ejemplo:
http://bioleft.datalud.com/admin/structure/semilla/13791
