### ISSUE TITLE
 La palabra gramos está mal abreviada

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#3]
**Problema:**
Hay varias instancias de la abreviación gramos mál, aparece como "grs" y debería ser "g".

**Comportamiento deseado**
-Que las abreviaciones estén gramaticalmente bien

** Sugerencia**
-No abreviar las palabras para un mejor entendimiento si es que hay suficiente espacio.

**Links:**
RAE: http://www.rae.es/diccionario-panhispanico-de-dudas/apendices/simbolos-alfabetizables
Grs:

1. * Problema similar en catalogo de semillas https://plataforma.bioleft.org/catalogo-semillas
2. * https://plataforma.bioleft.org/admin/structure/semilla/add/mis_semillas

Nota: puede que haya más instancias pero no han sido detectadas.

**Comment by ludwigrubio** [comment]
Se cambió por "gramos".
Además siguiendo la recomendación ,la abreviación "nro." en el filtro superior, se cambió por número.

**Comment by fernandiie** [comment]
Verificado. La palabra gramos ahora no aparece abreviada en los siguientes enlaces: 

**Catálogo de semillas:** http://bioleft.datalud.com/catalogo-semillas
**Mis semillas:** http://bioleft.datalud.com/mis-semillas
**Añadir semillas:** http://bioleft.datalud.com/admin/structure/semilla/add/mis_semillas

**Nota:**
Los enlaces de arriba son provisionales.
