### ISSUE TITLE
El menú principal no se importa al crear el sitio

### ISSUE THREAD

**Issue by ludwigrubio** [ludwigrubio/bioleft#4]
Se requiere que al momento de instalar el sitio se cuente con un menú de navegación básico que permita acceder a las principales funcionalidad del sitio.

**Comment by mpadilla** [comment]
Parece que los links del menú no se pueden exportar con features.
https://www.drupal.org/project/features/issues/2383453

**Comment by ludwigrubio** [comment]
Queda documentado como parte del proceso del contenido inicial en __documentacion.md__
