### ISSUE TITLE
"El sitio web encontró un error inesperado..." aparece cuando se ordena por especie

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#8]
**Problema:**
El sitio falló de manera inesperada con el mensaje "El sitio web encontró un error inesperado. Vuelva a intentarlo más tarde."  Esto sucedio despues de haber hecho clic sobre la columna "especie". Había solo una semilla creada y este campo estaba vacío. Después de crear más semillas con todos los campos completados* se siguió observando el mismo comportamiento. 

*Especie	Cultivar	Biolefter / Usuario	Licencia	Cantidad

**Comportamiento deseado**
-Que la plataforme pueda manejar las fallas de una mejor manera
-Que las semillas se puedan ordenar por cualquier columna aunque hayan celdas con información vacía.

**Links:** 
Mis semillas: https://plataforma.bioleft.org/mis-semillas
Error inesperado: https://plataforma.bioleft.org/mis-semillas?order=views_conditional_field_1&sort=asc

**Comment by ludwigrubio** [comment]
Debido a que se trata de un error de integración del módulo field_conditional con views, se des-habilito la posibilidad de ordenar para los campos "Especie" y "Cultivar".

**Comment by fernandiie** [comment]
Verificado, ahora no se puede ordenar por los campos "Especie" y "Cultivar".

Enlace provisional donde se verificó:
http://bioleft.datalud.com/mis-semillas
