### ISSUE TITLE
Registro de nuevo usuario - Mensajes de ayuda en inglés 

### ISSUE THREAD

**Issue by fernandiie** [ludwigrubio/bioleft#9]
**Problema:**
Cuando una persona intenta registrarse por primera vez y olvida llenar algunos campos obligatorios aparecen unos mensajes de aydua en inglés, por ejemplo si no se introduce la dirección "Please fill out this field".

**Comportamiento deseado**
-Que los mensajes aparezcan en el idioma de la página, en este caso en español. 

**Links:** 
https://plataforma.bioleft.org/user/register

**Comment by ludwigrubio** [comment]
No fue posible replicar este error, puede deberse a que hay mensajes de campos obligatorios que provienen de la configuración de idioma del navegador que se esté usando.

**Comment by fernandiie** [comment]
Efectivamente se hicieron distintas pruebas en 2 navegadores distintos y no se pudo reproducir el error. Por otro lado también se intentó los mismos escenarios en una versión de la aplicación más reciente y tampoco se pudo recrear. 

Todos los mensajes aparecieron en español respectivamente.
